# Site settings
title: Victor H Mendes Photography # Your brand name
description: Fine Art Photography - Capturing Beauty in the Imperfect # Your tagline
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.victorhmendes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima # You can keep minima or remove this line to not use a default theme
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom variables (use these in your templates)
author: Victor H Mendes
#email: your.email@example.com
#instagram_url: https://instagram.com/your_instagram
#etsy_url: https://yourshop.etsy.com
